### ISSUE TITLE
Add MP ontology to KG

### ISSUE THREAD

**Issue by computationdoc** [hubmapconsortium/ontology-api#101]
Kids First team doing their own version of this import. After initial code failed for 24 lines in nmCUI in JCS OWLNETS-GRAPH code this should be fixed and added possibly by HuBMAP rather than only in kids first version either using their code or fixing OWL file or our code or OWLNETS, wherever the issue is.

**Comment by AlanSimmons** [comment]
Corrected as part of refactoring of ontology. MP is now ingested without issue.
