### ISSUE TITLE
Develop cypher for variable length CUI-CUI API

### ISSUE THREAD

**Issue by computationdoc** [hubmapconsortium/ontology-api#108]
Develop cypher for variable length CUI-CUI API with parameters for relationship types list and SABs list - and possibly max number of relationship - this enables robust descendent-like and ancestor-like queries for any type - use careful attention to cardinality/take advantage of this: see 'DISTINCT nodes from variable-length paths' section toward the end of: https://neo4j.com/developer/kb/understanding-cypher-cardinality/

**Comment by AlanSimmons** [comment]
Moving to ubkg repo.
