### ISSUE TITLE
Integrate Ontology for assay_types into Ne04j db

### ISSUE THREAD

**Issue by ChuckKollar** [hubmapconsortium/ontology-api#113]
This information needs to be converted to .tsv files of the same flavor as Tiffany's PheKnowLator output for the Neo4j import process through Jonathan's code.

This is the source information for the ontology:
https://github.com/hubmapconsortium/search-api/blob/test-release/src/search-schema/data/definitions/enums/assay_types.yaml

**Comment by AlanSimmons** [comment]
This is the core functionality of the script in https://github.com/hubmapconsortium/ontology-api/tree/main/scripts/skowlnets

**Comment by AlanSimmons** [comment]
This has been completed.
