### ISSUE TITLE
Update ontology-api-spec.yaml

### ISSUE THREAD

**Issue by ChuckKollar** [hubmapconsortium/ontology-api#121]
For the ontology-api-spec.yaml, update summary, examples, descriptions, for the endpoints and components to make them more consistent with what the Ne04j is doing.

Updated version of API to 1.1.2, and it is available on SmartAPI  https://smart-api.info/ui/dea4bf91545a51b3dc415ba37e2a9e4e

https://github.com/hubmapconsortium/ontology-api/pull/132

**Comment by computationdoc** [comment]
I did many changes by editing into a branch - please update live if possible - there are too many changes for me to continue without an update - its become confusing with the many deletions and changes - I'd like to see it updated now if possible - thanks!

**Comment by computationdoc** [comment]
there will need to be a bunch more changes as we work through this, but I think those I did for now are good for now - the more complex ones we were doing for the widget with the "termresponseobject" have the problem of potentially "blowing up to too slow I think" - we need to evaluate each one so I leaned on the side of deleting many we may want in future - so I took a very conservative approach...so far
