### ISSUE TITLE
Update to CCF 2.0

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/ontology-api#135]
CCF 2.0 should be released this month. There may be some additional changes need to support CCF in the ontology-api. The near-final ccf.owl is here: https://github.com/hubmapconsortium/ccf-ontology/blob/main/ccf.owl . There is a subset of ccf.owl called the "biological structure ontology" that just includes the asct+b tables here: https://github.com/hubmapconsortium/ccf-ontology/blob/main/ccf-bso.owl in case you want to use the subset (which may or may not make sense).

**Comment by AlanSimmons** [comment]
Completed some time ago.
