### ISSUE TITLE
Feature: tree based faceted search for anatomy 

### ISSUE THREAD

**Issue by JAH386** [hubmapconsortium/ontology-api#136]
Requires a “different tree” – KG use case – write query – Assay – response to NIH

JH to get more information from JS to provide clarity for BS

**Comment by AlanSimmons** [comment]
@shirey @computationdoc @JAH386 
This is a mysterious request. Can we close it?

**Comment by JAH386** [comment]
@AlanSimmons, Since this is nearly 9 months old I would say yes but I would defer to yourself, @computationdoc or @shirey.

**Comment by shirey** [comment]
I don't have any recollection of this or the context, will close..
