### ISSUE TITLE
Build new CSV files using Alan's script

### ISSUE THREAD

**Issue by ChuckKollar** [hubmapconsortium/ontology-api#145]
We will use the old UMLS-CSVs-2020AB that Jonathan provided as seed CSVs for this process. We will build a new set of CSVs that include processing from Alan's new code.

./build_csv.sh -v PATO UBERON CL DOID CCFASCTB OBI EDAM HSAPDV SBO MI CHEBI MP ORDO PR UNIPROTKB BAO SWO CHMO

**Comment by AlanSimmons** [comment]
The build script needs the parameter HUBMAP--i.e.,

./build_csv.sh -v PATO UBERON CL DOID CCFASCTB OBI EDAM HSAPDV SBO MI CHEBI MP ORDO PR UNIPROTKB BAO SWO CHMO **HUBMAP**

**Comment by AlanSimmons** [comment]
New script and input spreadsheet available in:

https://github.com/hubmapconsortium/ontology-api/tree/main/scripts/skowlnets

Execution triggered by entries in ontologies.json.

**Comment by AlanSimmons** [comment]
All components to complete this task appear to be ready for testing.
1. New script to convert application ontology data for HuBMAP (via a SimpleKnowledge spreadsheet).
2. New script to generate UMLS CSVs. CSVs for the UMLS2022AB have been generated.
3. The ontologies.json file has been updated to account for HuBMAP.

**Comment by AlanSimmons** [comment]
This is completed.
