### ISSUE TITLE
Spin up an Ontology Neo4j container on DEV using CSVs from a build using Alan's script

### ISSUE THREAD

**Issue by ChuckKollar** [hubmapconsortium/ontology-api#146]
see precondition ontology-api#145

**Comment by AlanSimmons** [comment]
1. UMLS CSVs are now generated from a Python script. CSVs for the UMLS2021AB are available.
2. Script to generate OWLNETS-compatible files for HuBMAP ontology is now available.
3. ontologies.json file updated to direct build_csv.py to generate nodes and edges for HubMAP ontology.

**Comment by AlanSimmons** [comment]
Generation architecture (build_csv.sh > build_csv.py > OWLNETS generation scripts > UMLS OWLNETS generation script > CSV files) now includes HuBMAP step. 

CSV files, including modifications related to HuBMAP, load successfully into neo4j.

Thus, DEV instance can be instantiated via Docker file, theoretically. 

Issues:

1. The UMLS OWLNETS script overwrites isa assignments for HuBMAP concepts with dbxref code. 
2. Question over whether Docker based neo4j with UMLS node content complies with UMLS licensing.

**Comment by shirey** [comment]
Finished a while ago under a different issue, yes we'll close. thanks @AlanSimmons
