### ISSUE TITLE
Ontology: Test Ontology Neo4j on DEV built using CSVs built using Alan's script

### ISSUE THREAD

**Issue by ChuckKollar** [hubmapconsortium/ontology-api#147]
It would be nice if this testing created the beginnings of some scripts that could run after every build verifying expected relationships that should be in the database.

**Comment by AlanSimmons** [comment]
TESTS: 

1. match p=()-[r {SAB:'X'}]-() Return p limit 10

where X is in 
(PATO UBERON CL DOID CCFASCTB OBI EDAM HSAPDV SBO MI CHEBI MP ORDO PR UNIPROTKB BAO SWO CHMO HUBMAP)

2. match p=()-[:X]-() return p limit 10 
where X in 
(has_representation,
contains,
implements,
has_interface,
assay_type,
has_preparation_method,
has_form,
has_analyte)

**Comment by AlanSimmons** [comment]
John generated a set of UMLS CSV files to [this path](https://pitt-my.sharepoint.com/personal/milnes_pitt_edu/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fmilnes%5Fpitt%5Fedu%2FDocuments%2FUMLSGraphExtracts%2FUMLS%2DGraph%2Etar&parent=%2Fpersonal%2Fmilnes%5Fpitt%5Fedu%2FDocuments%2FUMLSGraphExtracts&ct=1660678198478&or=OWA%2DNT&cid=4e8f02d5%2Ddf5c%2Dea52%2D0fd2%2D44d5bf93f09b&ga=1).

**Comment by AlanSimmons** [comment]
Script for converting HuBMAP specific ontology is [here](https://github.com/hubmapconsortium/ontology-api/tree/main/scripts/skowlnets).

**Comment by AlanSimmons** [comment]
Version of an ontology input spreadsheet for HuBMAP is [here](https://github.com/hubmapconsortium/ontology-api/tree/main/scripts/skowlnets).

**Comment by AlanSimmons** [comment]
ontologies.json file updated to direct generation of HuBMAP-specific OWLNETS files. PR at https://github.com/hubmapconsortium/ontology-api/pull/149
