### ISSUE TITLE
Load latest working version of Ontology onto PROD

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ontology-api#154]

**Comment by AlanSimmons** [comment]
@shirey Latest version of neo4j graph has the following integrations:


UBERON
PATO
CL
DOID
OBI
EDAM
HSAPDV
SBO
MI
CHEBI
MP (fixed)
ORDO
UNIPROTKB (new; custom)
PR (fixed)
UO (new)
HUSAT (new)
HUBMAP (new)
CCF (new version)

**Comment by AlanSimmons** [comment]
@yuanzhou I have an archive of CSV files that can be copied to the prod neo4j instance to build a new ontology database.

**Comment by yuanzhou** [comment]
@shirey @AlanSimmons I'm thinking we should do a rebuild on DEV VM first along with the recent ontology-api updates. And once you and @ChuckKollar give me the green light, I can copy over the neo4j data directory generated on DEV to PROD and release the ontology-api as well.

**Comment by AlanSimmons** [comment]
Rebuilding in the DEV VM requires access that I do not have--e.g., 

`Go to the host and update from the repository.

$ ssh -i ~/.ssh/id_rsa_e2c.pem cpk36@neo4j.dev.hubmapconsortium.org
$ sudo /bin/su - centos
$ cd hubmap/ontology-api
# NOTE: this is a Git reposntory https://github.com/hubmapconsortium/ontology-api.git so make sure that you are in the right branch...
$ git pull`

**Comment by AlanSimmons** [comment]
The code snippet is from the instructions in the `[readme](https://github.com/hubmapconsortium/ontology-api/tree/main/neo4j#readme)`.

**Comment by yuanzhou** [comment]
@AlanSimmons I can rebuild the ontology neo4j on DEV. @ChuckKollar can you rebuild the ontology-api on DEV since I don't know much about the recent changes?
