### ISSUE TITLE
UBKG REST API (HM & DD) through AWS API Gateway

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/ontology-api#179]
Currently the ontology-api is routed via the "old gateway", will move to use AWS API Gateway with custom domains for both HuBMAP and Data Distillery ubkg-api.

**Comment by AlanSimmons** [comment]
@yuanzhou Will this change affect the [SmartAPI](https://smart-api.info/ui/dea4bf91545a51b3dc415ba37e2a9e4e) configuration? 

In particular, the SmartAPI documentation should reflect the new _valueset_ endpoint.

**Comment by yuanzhou** [comment]
> @yuanzhou Will this change affect the [SmartAPI](https://smart-api.info/ui/dea4bf91545a51b3dc415ba37e2a9e4e) configuration?
> 
> In particular, the SmartAPI documentation should reflect the new _valueset_ endpoint.

@AlanSimmons This change will not affect the SMART API configuration. The Smart API pulls the definitions from the https://github.com/hubmapconsortium/ontology-api/blob/main/ontology-api-spec.yaml currently. However, we'll be switching to use https://github.com/dbmi-pitt/ubkg/blob/main/ubkg-api-spec.yaml once we deploy the UBKG API. 

The HuBMAP and Data Distillery are sharing the same yaml at this point, this is something we'll have to think about and handle properly if they will have different endpoint definitions down the road.
