### ISSUE TITLE
Create "graph-version-node" while building graph

### ISSUE THREAD

**Issue by cborromeo** [hubmapconsortium/ontology-api#23]
We need to track the "source information" used to build the Knowledge Graph (ex: UMLS version 2020AB, CCF version xyz, etc.)  We should probably insert nodes into the graph.  We can use these nodes to verify a successful deployment and to inform users of the data used to build the graph.

**Comment by computationdoc** [comment]
We changed direction on this - we decided that the graph itself will not have internal version knowledge - we decided that the API querying the graph will manage versions - that current plan is to keep old versions running with "version X" as parameter in the API "semantic gateway" that will route to appropriate deployed version of the graph
