### ISSUE TITLE
Build PheKnowLator data from OWLNETS

### ISSUE THREAD

**Issue by cborromeo** [hubmapconsortium/ontology-api#31]
Use the OWLNETS application to build the export of UBERON and CL data

**Comment by computationdoc** [comment]
From issue #33 - a small part of this is to generate the new relations in the table to include all the relations of that ontology

**Comment by computationdoc** [comment]
This is BLOCKED pending a new release of OWLNETS that Tiffany Callahan is working through to do one ontology from OBO at a time - the tool does it via private APIs she needs to surface.

**Comment by computationdoc** [comment]
Received new OWLNETS code / Jupyter notebook from Tiffany Callahan so can build using refactored code...need to do trial of it!
