### ISSUE TITLE
Submit to OBI relating to HuBMAP assays

### ISSUE THREAD

**Issue by pecan88** [hubmapconsortium/ontology-api#48]
Add HuBMAP assays that are not in OBI by working with Michelle Giglio at CFDE.

Request from @computationdoc on Feb 3, 2021.

**Comment by computationdoc** [comment]
Submit HuBMAP Assays not in OBI, to OBI via BioPortal, for OBI consideration

**Comment by AlanSimmons** [comment]
ChIP-Seq - has NCI, but no OBI
SIMS-IMS
MxIF - has NCI, no OBI
rnaSEQ - MSH, no OBI
10x-genomics?
SCI-seq
SnapATAC

**Comment by AlanSimmons** [comment]
Moved to ubkg repo.
