### ISSUE TITLE
Prepare and send updated CUIs and Semantic Types to UBERON and CL

### ISSUE THREAD

**Issue by computationdoc** [hubmapconsortium/ontology-api#50]

**Comment by computationdoc** [comment]
This can be done now (was previously blocked by not having complete FREEZE code and database verified). This involves querying the graph for CUIs connected to UBERON and CL and their TUIs before and after TUI assignment - TUI assignment is issue #80

**Comment by AlanSimmons** [comment]
Moving to ubkg.
