### ISSUE TITLE
Add Uniprot-HGNC codes and relationships (from Uniprot mapping) to KG

### ISSUE THREAD

**Issue by computationdoc** [hubmapconsortium/ontology-api#52]
This will serve queries from Antibody database translation to genes so RRIDs with Uniprot will connect to gene to "B" of ASCT+B

**Comment by computationdoc** [comment]
Part of this activity is to evaluate if issue #100 supersedes this - if oR successful and contains all relevant Human UniProt IDs to HGNC then this not needed.

**Comment by computationdoc** [comment]
The activity of evaluating whether we do issue #52 or issue #100 is completed. We will do both based upon my conversation with Neil K regarding antibody leadership today its my decision that we need higher priority this one #52 but we will also pursue adding the PR Ontology #100 at lower priority.

**Comment by AlanSimmons** [comment]
Assertions for UNIPROTKB proteins to HGNC genes has been added to the ontology KG.
