### ISSUE TITLE
Secure Onotology API behind HuBMAP gateway

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ontology-api#64]
Currently both the RESTful server and Ne04j databases are running on DEV dockerized and using nginx. Here we add authentication and authorization through Globus.

Create a TEST instance and publish through the gateway with HuBMAP-Read group access needed for all methods/endpoints at https://ontology-api.test.hubmapconsortium.org

**Comment by yuanzhou** [comment]
Will upgrade the current `neo4j-dev-test-stage` to have 32G RAM.
