### ISSUE TITLE
Add additional ontologies to Neo4j database via .csv files

### ISSUE THREAD

**Issue by ChuckKollar** [hubmapconsortium/ontology-api#72]
UBERON_OWL_URL, CL_OWL_URL, CHEBL_OWL_URL, PATO_OWL_URL, DOID_OWL_URL, OBI_OWL_URL, CCF_OWL_URL

**Comment by shirey** [comment]
Closing as it is now superseded by: https://github.com/hubmapconsortium/ontology-api/issues/79
