### ISSUE TITLE
Add remaining ontologies

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ontology-api#79]
Add the remaining ontologies to the database including:
 -  ASCTB_TEMP (CCF)
 - @computationdoc what other ontologies are needed, please edit this

Yes, this is subject to getting the ontologies and the ordering from Jonathan. There will possibly be some iterations where things break, but possibly not.

**Comment by computationdoc** [comment]
We have succeeded with MVP plus, which included PATO,UBERON,CL,DOID,CCF-ASCTB,OBI,EDAM,HSAPDV,SBO,MI,CHEBI
