### ISSUE TITLE
Properly capture Code and CUI labels

### ISSUE THREAD

**Issue by ChuckKollar** [hubmapconsortium/ontology-api#82]
Fix where new CUI-SUIs and new CODE-SUIs times two would match an OLD SUI not a new SUI (and therefore in current code don't get written - because they don't match a new SUI)  - does this alone explain 2439 CUIs with no Pref_term and similar numbers of Codes with no PT? - i think it does so needs fix and then re-test

**Comment by bherr2** [comment]
Don't forget the TPS reports! :laughing:

**Comment by computationdoc** [comment]
Fixed and retested and verified fix in new FREeZE KG for Kids First
