### ISSUE TITLE
HuBMAP Application Ontology: Organs

### ISSUE THREAD

**Issue by ChuckKollar** [hubmapconsortium/ontology-api#90]
We need support the various HuBMAP specific organ enums to the ontology.  [@computationdoc do you have links to the multiple organ definition yaml files?]

Jonathan has started a spreadsheet (https://docs.google.com/spreadsheets/d/1OChRIHy5DnMI4CBesc9XsNs8TLrEmDiPViEV1gt8r2s/edit#gid=0) that we can directly export 2 csv files for direct use by the Neo4j import step when creating the KG database.  [@computationdoc Need Link To Spreadsheet].  This spreadsheet will need to be finished, files exported and added to KG build (and KG built!).

=======================
`Previously titled:`  Mapping HubMap Enum sets to ontology terms
`with this information:`
From Jonathan: I would give him the cypher for enum thing - but it's basically possibly just the existing term->code Endpoint?

Mapping the codes from these files to actual ontology terms (non-programming task):
https://github.com/hubmapconsortium/search-api/tree/test-release/src/search-schema/data/definitions/enums
organ_types.yml is the subject here.

NOTE: Find a UBERON URL to map to the same Concept that the description is mapped.

**Comment by AlanSimmons** [comment]
Organ data from organ_types.yaml incorporated into https://github.com/hubmapconsortium/ontology-api/tree/main/scripts/skowlnets
