### ISSUE TITLE
Grab the http download that Jonathan's code save it and Jonathan's code will use that file.

### ISSUE THREAD

**Issue by ChuckKollar** [hubmapconsortium/ontology-api#92]
To be consistent with the way that we are doing everything from a local file (cached).

**Comment by computationdoc** [comment]
This is for RO.json file OWLNETS-GRAPH reads on the fly from Internet. Should be pre-downloaded.

**Comment by computationdoc** [comment]
Accidentally closed issue when commenting and moving to backlog

**Comment by AlanSimmons** [comment]
The OWLNETS-UMLS-GRAPH downloads ro.json from
https://raw.githubusercontent.com/oborel/obo-relations/master/ro.json and works with it locally. This card can be closed.
