### ISSUE TITLE
Address OWLNETS files that are non-conformant TSVs

### ISSUE THREAD

**Issue by ChuckKollar** [hubmapconsortium/ontology-api#96]
In the TSV file a "record" is composed of "fields", the fields are separated by tabs, and the records are delineated by a return character. It appears that the PheKnowLator code does not make sure that the "fields" contain NO return characters so the net effect is broken records.

The task here is to make sure that there are no broken records by removing the record separator character when it appears in a field.

**Comment by computationdoc** [comment]
This was completed and works successfully. Should be either in review by other developer or closed because I’ve verified it solved issue.

**Comment by AlanSimmons** [comment]
@shirey Can we close this?

**Comment by shirey** [comment]
Yes, thanks @AlanSimmons
